; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

	TITLE	f:\windowsandbox\windowsandbox\src\entrypoint.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_07HLLGMCO@Sandbox@			; `string'
EXTRN	__imp__GetMessageA@16:PROC
EXTRN	__imp__DispatchMessageA@4:PROC
EXTRN	___std_terminate:PROC
EXTRN	__imp__TranslateMessage@4:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	___CxxFrameHandler3:PROC
;	COMDAT ??_C@_07HLLGMCO@Sandbox@
CONST	SEGMENT
??_C@_07HLLGMCO@Sandbox@ DB 'Sandbox', 00H		; `string'
CONST	ENDS
PUBLIC	?__autoclassinit2@Window@@QAEXI@Z		; Window::__autoclassinit2
PUBLIC	_WinMain@16
PUBLIC	__real@4202a05f20000000
PUBLIC	__xmm@7fffffffffffffff7fffffffffffffff
EXTRN	__CxxThrowException@8:PROC
EXTRN	_memcpy:PROC
EXTRN	_memmove:PROC
EXTRN	_memset:PROC
EXTRN	___security_cookie:DWORD
EXTRN	__fltused:DWORD
;	COMDAT __xmm@7fffffffffffffff7fffffffffffffff
CONST	SEGMENT
__xmm@7fffffffffffffff7fffffffffffffff DB 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH
	DB	0ffH, 07fH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 07fH
CONST	ENDS
;	COMDAT __real@4202a05f20000000
CONST	SEGMENT
__real@4202a05f20000000 DQ 04202a05f20000000r	; 1e+10
CONST	ENDS
END
