; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

	TITLE	f:\windowsandbox\windowsandbox\src\entrypoint.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_07HLLGMCO@Sandbox@			; `string'
PUBLIC	??_C@_0BD@BEPCMMME@Standard?5Exception@		; `string'
PUBLIC	??_C@_0BC@BLOAIJL@Unknown?5Exception@		; `string'
PUBLIC	??_C@_0BF@KKBOEDFD@No?5Details?5Available@	; `string'
PUBLIC	___pobjectentrylast
PUBLIC	___pobjectentryfirst
PUBLIC	___pobjectentrymid
PUBLIC	??_R0?AVException@@@8				; Exception `RTTI Type Descriptor'
PUBLIC	??_R0?AVexception@std@@@8			; std::exception `RTTI Type Descriptor'
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	___std_terminate:PROC
EXTRN	??3@YAXPAXI@Z:PROC				; operator delete
EXTRN	__imp__MessageBoxA@16:PROC
EXTRN	??_M@YGXPAXIIP6EX0@Z@Z:PROC			; `eh vector destructor iterator'
EXTRN	??_V@YAXPAXI@Z:PROC				; operator delete[]
EXTRN	@__security_check_cookie@4:PROC
EXTRN	___CxxFrameHandler3:PROC
;	COMDAT ??_R0?AVexception@std@@@8
data$r	SEGMENT
??_R0?AVexception@std@@@8 DD FLAT:??_7type_info@@6B@	; std::exception `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVexception@std@@', 00H
data$r	ENDS
;	COMDAT ??_R0?AVException@@@8
data$r	SEGMENT
??_R0?AVException@@@8 DD FLAT:??_7type_info@@6B@	; Exception `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVException@@', 00H
data$r	ENDS
;	COMDAT ___pobjectentrymid
minATL$__m	SEGMENT
___pobjectentrymid DD 00H
minATL$__m	ENDS
;	COMDAT ___pobjectentryfirst
minATL$__a	SEGMENT
___pobjectentryfirst DD 00H
minATL$__a	ENDS
;	COMDAT ___pobjectentrylast
minATL$__z	SEGMENT
___pobjectentrylast DD 00H
minATL$__z	ENDS
;	COMDAT ??_C@_0BF@KKBOEDFD@No?5Details?5Available@
CONST	SEGMENT
??_C@_0BF@KKBOEDFD@No?5Details?5Available@ DB 'No Details Available', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BC@BLOAIJL@Unknown?5Exception@
CONST	SEGMENT
??_C@_0BC@BLOAIJL@Unknown?5Exception@ DB 'Unknown Exception', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@BEPCMMME@Standard?5Exception@
CONST	SEGMENT
??_C@_0BD@BEPCMMME@Standard?5Exception@ DB 'Standard Exception', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_07HLLGMCO@Sandbox@
CONST	SEGMENT
??_C@_07HLLGMCO@Sandbox@ DB 'Sandbox', 00H		; `string'
CONST	ENDS
PUBLIC	?__autoclassinit2@Game@@QAEXI@Z			; Game::__autoclassinit2
PUBLIC	??1Game@@QAE@XZ					; Game::~Game
PUBLIC	_WinMain@16
PUBLIC	__real@00000000
PUBLIC	__real@32cd365b
PUBLIC	__real@348bdd11
PUBLIC	__real@3638b88e
PUBLIC	__real@37cfb4c2
PUBLIC	__real@39500bf1
PUBLIC	__real@3ab609aa
PUBLIC	__real@3b800000
PUBLIC	__real@3c088886
PUBLIC	__real@3d2aaaa3
PUBLIC	__real@3e22f983
PUBLIC	__real@3e2aaaab
PUBLIC	__real@3f000000
PUBLIC	__real@3f800000
PUBLIC	__real@3fc90fdb
PUBLIC	__real@40490fdb
PUBLIC	__real@40c90fdb
PUBLIC	__real@41cdcd6500000000
PUBLIC	__real@4202a05f20000000
PUBLIC	__real@43088e6d68b00000
PUBLIC	__real@4e6e6b28
PUBLIC	__real@bf800000
PUBLIC	__real@bfc90fdb
PUBLIC	__real@c0490fdb
PUBLIC	__xmm@00000000000000003f8000003f800000
PUBLIC	__xmm@000000003f8000003f8000003f800000
PUBLIC	__xmm@000000003f800000bf8000003f800000
PUBLIC	__xmm@00000000bf8000003f8000003f800000
PUBLIC	__xmm@00000000bf800000bf8000003f800000
PUBLIC	__xmm@3f800000000000003f800000bf800000
PUBLIC	__xmm@3f800000000000004400000044000000
PUBLIC	__xmm@3f8000003f0000003f0000003f000000
PUBLIC	__xmm@3f8000003f8000003f800000bf800000
PUBLIC	__xmm@3f80000040a000000000000000000000
PUBLIC	__xmm@3f800000bf8000000000000000000000
PUBLIC	__xmm@3f800000bf8000003f80000000000000
PUBLIC	__xmm@7fffffffffffffff7fffffffffffffff
PUBLIC	__xmm@80000000800000008000000080000000
PUBLIC	__xmm@bf06bca23f86bca23f8000003f800000
PUBLIC	__xmm@bf800000bf800000000000003f800000
PUBLIC	__xmm@bf800000bf8000003f8000003f800000
EXTRN	__CxxThrowException@8:PROC
EXTRN	__alldiv:PROC
EXTRN	__alldvrm:PROC
EXTRN	__allmul:PROC
EXTRN	__ltod3:PROC
EXTRN	_memcpy:PROC
EXTRN	_memmove:PROC
EXTRN	_memset:PROC
EXTRN	___security_cookie:DWORD
EXTRN	__fltused:DWORD
;	COMDAT __xmm@bf800000bf8000003f8000003f800000
CONST	SEGMENT
__xmm@bf800000bf8000003f8000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 080H
	DB	'?', 00H, 00H, 080H, 0bfH, 00H, 00H, 080H, 0bfH
CONST	ENDS
;	COMDAT __xmm@bf800000bf800000000000003f800000
CONST	SEGMENT
__xmm@bf800000bf800000000000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 00H
	DB	00H, 00H, 00H, 080H, 0bfH, 00H, 00H, 080H, 0bfH
CONST	ENDS
;	COMDAT __xmm@bf06bca23f86bca23f8000003f800000
CONST	SEGMENT
__xmm@bf06bca23f86bca23f8000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 080H
	DB	'?', 0a2H, 0bcH, 086H, '?', 0a2H, 0bcH, 06H, 0bfH
CONST	ENDS
;	COMDAT __xmm@80000000800000008000000080000000
CONST	SEGMENT
__xmm@80000000800000008000000080000000 DB 00H, 00H, 00H, 080H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 080H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __xmm@7fffffffffffffff7fffffffffffffff
CONST	SEGMENT
__xmm@7fffffffffffffff7fffffffffffffff DB 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH
	DB	0ffH, 07fH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 07fH
CONST	ENDS
;	COMDAT __xmm@3f800000bf8000003f80000000000000
CONST	SEGMENT
__xmm@3f800000bf8000003f80000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 080H
	DB	'?', 00H, 00H, 080H, 0bfH, 00H, 00H, 080H, '?'
CONST	ENDS
;	COMDAT __xmm@3f800000bf8000000000000000000000
CONST	SEGMENT
__xmm@3f800000bf8000000000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	00H, 00H, 00H, 080H, 0bfH, 00H, 00H, 080H, '?'
CONST	ENDS
;	COMDAT __xmm@3f80000040a000000000000000000000
CONST	SEGMENT
__xmm@3f80000040a000000000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	00H, 00H, 00H, 0a0H, '@', 00H, 00H, 080H, '?'
CONST	ENDS
;	COMDAT __xmm@3f8000003f8000003f800000bf800000
CONST	SEGMENT
__xmm@3f8000003f8000003f800000bf800000 DB 00H, 00H, 080H, 0bfH, 00H, 00H, 080H
	DB	'?', 00H, 00H, 080H, '?', 00H, 00H, 080H, '?'
CONST	ENDS
;	COMDAT __xmm@3f8000003f0000003f0000003f000000
CONST	SEGMENT
__xmm@3f8000003f0000003f0000003f000000 DB 00H, 00H, 00H, '?', 00H, 00H, 00H
	DB	'?', 00H, 00H, 00H, '?', 00H, 00H, 080H, '?'
CONST	ENDS
;	COMDAT __xmm@3f800000000000004400000044000000
CONST	SEGMENT
__xmm@3f800000000000004400000044000000 DB 00H, 00H, 00H, 'D', 00H, 00H, 00H
	DB	'D', 00H, 00H, 00H, 00H, 00H, 00H, 080H, '?'
CONST	ENDS
;	COMDAT __xmm@3f800000000000003f800000bf800000
CONST	SEGMENT
__xmm@3f800000000000003f800000bf800000 DB 00H, 00H, 080H, 0bfH, 00H, 00H, 080H
	DB	'?', 00H, 00H, 00H, 00H, 00H, 00H, 080H, '?'
CONST	ENDS
;	COMDAT __xmm@00000000bf800000bf8000003f800000
CONST	SEGMENT
__xmm@00000000bf800000bf8000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 080H
	DB	0bfH, 00H, 00H, 080H, 0bfH, 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT __xmm@00000000bf8000003f8000003f800000
CONST	SEGMENT
__xmm@00000000bf8000003f8000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 080H
	DB	'?', 00H, 00H, 080H, 0bfH, 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT __xmm@000000003f800000bf8000003f800000
CONST	SEGMENT
__xmm@000000003f800000bf8000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 080H
	DB	0bfH, 00H, 00H, 080H, '?', 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT __xmm@000000003f8000003f8000003f800000
CONST	SEGMENT
__xmm@000000003f8000003f8000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 080H
	DB	'?', 00H, 00H, 080H, '?', 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT __xmm@00000000000000003f8000003f800000
CONST	SEGMENT
__xmm@00000000000000003f8000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 080H
	DB	'?', 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT __real@c0490fdb
CONST	SEGMENT
__real@c0490fdb DD 0c0490fdbr			; -3.14159
CONST	ENDS
;	COMDAT __real@bfc90fdb
CONST	SEGMENT
__real@bfc90fdb DD 0bfc90fdbr			; -1.5708
CONST	ENDS
;	COMDAT __real@bf800000
CONST	SEGMENT
__real@bf800000 DD 0bf800000r			; -1
CONST	ENDS
;	COMDAT __real@4e6e6b28
CONST	SEGMENT
__real@4e6e6b28 DD 04e6e6b28r			; 1e+09
CONST	ENDS
;	COMDAT __real@43088e6d68b00000
CONST	SEGMENT
__real@43088e6d68b00000 DQ 043088e6d68b00000r	; 8.64e+14
CONST	ENDS
;	COMDAT __real@4202a05f20000000
CONST	SEGMENT
__real@4202a05f20000000 DQ 04202a05f20000000r	; 1e+10
CONST	ENDS
;	COMDAT __real@41cdcd6500000000
CONST	SEGMENT
__real@41cdcd6500000000 DQ 041cdcd6500000000r	; 1e+09
CONST	ENDS
;	COMDAT __real@40c90fdb
CONST	SEGMENT
__real@40c90fdb DD 040c90fdbr			; 6.28319
CONST	ENDS
;	COMDAT __real@40490fdb
CONST	SEGMENT
__real@40490fdb DD 040490fdbr			; 3.14159
CONST	ENDS
;	COMDAT __real@3fc90fdb
CONST	SEGMENT
__real@3fc90fdb DD 03fc90fdbr			; 1.5708
CONST	ENDS
;	COMDAT __real@3f800000
CONST	SEGMENT
__real@3f800000 DD 03f800000r			; 1
CONST	ENDS
;	COMDAT __real@3f000000
CONST	SEGMENT
__real@3f000000 DD 03f000000r			; 0.5
CONST	ENDS
;	COMDAT __real@3e2aaaab
CONST	SEGMENT
__real@3e2aaaab DD 03e2aaaabr			; 0.166667
CONST	ENDS
;	COMDAT __real@3e22f983
CONST	SEGMENT
__real@3e22f983 DD 03e22f983r			; 0.159155
CONST	ENDS
;	COMDAT __real@3d2aaaa3
CONST	SEGMENT
__real@3d2aaaa3 DD 03d2aaaa3r			; 0.0416666
CONST	ENDS
;	COMDAT __real@3c088886
CONST	SEGMENT
__real@3c088886 DD 03c088886r			; 0.00833333
CONST	ENDS
;	COMDAT __real@3b800000
CONST	SEGMENT
__real@3b800000 DD 03b800000r			; 0.00390625
CONST	ENDS
;	COMDAT __real@3ab609aa
CONST	SEGMENT
__real@3ab609aa DD 03ab609aar			; 0.00138884
CONST	ENDS
;	COMDAT __real@39500bf1
CONST	SEGMENT
__real@39500bf1 DD 039500bf1r			; 0.000198409
CONST	ENDS
;	COMDAT __real@37cfb4c2
CONST	SEGMENT
__real@37cfb4c2 DD 037cfb4c2r			; 2.47605e-05
CONST	ENDS
;	COMDAT __real@3638b88e
CONST	SEGMENT
__real@3638b88e DD 03638b88er			; 2.75256e-06
CONST	ENDS
;	COMDAT __real@348bdd11
CONST	SEGMENT
__real@348bdd11 DD 0348bdd11r			; 2.60516e-07
CONST	ENDS
;	COMDAT __real@32cd365b
CONST	SEGMENT
__real@32cd365b DD 032cd365br			; 2.38899e-08
CONST	ENDS
;	COMDAT __real@00000000
CONST	SEGMENT
__real@00000000 DD 000000000r			; 0
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$_WinMain@16 DD 019930522H
	DD	03H
	DD	FLAT:__unwindtable$_WinMain@16
	DD	01H
	DD	FLAT:__tryblocktable$_WinMain@16
	DD	2 DUP(00H)
	DD	00H
	DD	01H
__unwindtable$_WinMain@16 DD 0ffffffffH
	DD	00H
	DD	00H
	DD	FLAT:__unwindfunclet$_WinMain@16$4
	DD	0ffffffffH
	DD	00H
__tryblocktable$_WinMain@16 DD 00H
	DD	01H
	DD	02H
	DD	03H
	DD	FLAT:__catchsym$_WinMain@16$7
__catchsym$_WinMain@16$7 DD 09H
	DD	FLAT:??_R0?AVException@@@8
	DD	0ffffff60H
	DD	FLAT:__catch$_WinMain@16$0
	DD	09H
	DD	FLAT:??_R0?AVexception@std@@@8
	DD	0ffffff5cH
	DD	FLAT:__catch$_WinMain@16$1
	DD	040H
	DD	00H
	DD	00H
	DD	FLAT:__catch$_WinMain@16$2
xdata$x	ENDS
; Function compile flags: /Ogtp
;	COMDAT _WinMain@16
_TEXT	SEGMENT
_ex$2 = -164						; size = 4
_ex$3 = -160						; size = 4
_sandbox$4 = -156					; size = 136
__$ArrayPad$ = -20					; size = 4
__$EHRec$ = -16						; size = 16
_hInstance$ = 8						; size = 4
_hPrevInstance$ = 12					; size = 4
_pCmdLine$ = 16						; size = 4
_pCmdShow$ = 20						; size = 4
_WinMain@16 PROC					; COMDAT
; File F:\WindowSandbox\WindowSandbox\src\EntryPoint.cpp
; Line 9
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$_WinMain@16
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 152				; 00000098H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	ebx
	push	esi
	push	edi
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp+4]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR __$EHRec$[ebp], esp
	push	136					; 00000088H
	lea	eax, DWORD PTR _sandbox$4[ebp]
; Line 11
	mov	DWORD PTR __$EHRec$[ebp+12], 0
	push	0
	push	eax
	call	_memset
; Line 12
	lea	ecx, DWORD PTR _sandbox$4[ebp]
	call	??0Game@@QAE@HHPBD@Z			; Game::Game
; Line 13
	lea	ecx, DWORD PTR _sandbox$4[ebp]
	mov	BYTE PTR __$EHRec$[ebp+12], 1
	call	?Go@Game@@QAEHXZ			; Game::Go
	lea	ecx, DWORD PTR _sandbox$4[ebp]
	call	??1Window@@QAE@XZ			; Window::~Window
$LN14@WinMain:
; Line 24
	or	eax, -1
; Line 25
	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
__catch$_WinMain@16$0:
; Line 16
	mov	esi, DWORD PTR _ex$3[ebp]
	mov	ecx, esi
	mov	eax, DWORD PTR [esi]
	call	DWORD PTR [eax+8]
	mov	edx, DWORD PTR [esi]
	mov	ecx, esi
	mov	edi, eax
	call	DWORD PTR [edx+4]
	push	16					; 00000010H
	push	edi
	push	eax
	push	0
	call	DWORD PTR __imp__MessageBoxA@16
; Line 17
	mov	eax, $LN14@WinMain
	ret	0
__catch$_WinMain@16$1:
; Line 19
	mov	ecx, DWORD PTR _ex$2[ebp]
	push	16					; 00000010H
	push	OFFSET ??_C@_0BD@BEPCMMME@Standard?5Exception@
	mov	eax, DWORD PTR [ecx]
	call	DWORD PTR [eax+4]
	push	eax
	push	0
	call	DWORD PTR __imp__MessageBoxA@16
; Line 20
	mov	eax, $LN14@WinMain
	ret	0
__catch$_WinMain@16$2:
; Line 22
	push	16					; 00000010H
	push	OFFSET ??_C@_0BC@BLOAIJL@Unknown?5Exception@
	push	OFFSET ??_C@_0BF@KKBOEDFD@No?5Details?5Available@
	push	0
	call	DWORD PTR __imp__MessageBoxA@16
; Line 23
	mov	eax, $LN14@WinMain
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$_WinMain@16$4:
	lea	ecx, DWORD PTR _sandbox$4[ebp]
	jmp	??1Game@@QAE@XZ
	int	3
	int	3
	int	3
	int	3
	int	3
__ehhandler$_WinMain@16:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-168]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-8]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$_WinMain@16
	jmp	___CxxFrameHandler3
text$x	ENDS
_WinMain@16 ENDP
END
