; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

	TITLE	f:\windowsandbox\windowsandbox\src\tools\exception.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BC@JDPAADN@Regular?5Exception@		; `string'
PUBLIC	??_C@_07OFNLNJMF@?$FLLine?$FN?5@		; `string'
PUBLIC	??_C@_07DLGLNFOL@?$FLFile?$FN?5@		; `string'
;	COMDAT ??_C@_07DLGLNFOL@?$FLFile?$FN?5@
CONST	SEGMENT
??_C@_07DLGLNFOL@?$FLFile?$FN?5@ DB '[File] ', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_07OFNLNJMF@?$FLLine?$FN?5@
CONST	SEGMENT
??_C@_07OFNLNJMF@?$FLLine?$FN?5@ DB '[Line] ', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BC@JDPAADN@Regular?5Exception@
CONST	SEGMENT
??_C@_0BC@JDPAADN@Regular?5Exception@ DB 'Regular Exception', 00H ; `string'
PUBLIC	??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z ; std::basic_ostream<char,std::char_traits<char> >::operator<<
PUBLIC	??0exception@std@@QAE@XZ			; std::exception::exception
PUBLIC	?GetOriginString@Exception@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ ; Exception::GetOriginString
PUBLIC	?GetType@Exception@@UBEPBDXZ			; Exception::GetType
PUBLIC	?what@Exception@@UBEPBDXZ			; Exception::what
PUBLIC	??0Exception@@QAE@IPBD@Z			; Exception::Exception
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??0Exception@@QAE@IPBD@Z DQ 00000000019930522r ; 2.11987e-315
	DQ	00000000000000000r		; 0
	DQ	00000000000000000r		; 0
	DQ	00000000000000000r		; 0
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$?what@Exception@@UBEPBDXZ DQ 00000000119930522r ; 2.33398e-314
	DD	FLAT:__unwindtable$?what@Exception@@UBEPBDXZ
	DQ	00000000000000000r		; 0
	DQ	00000000000000000r		; 0
	DQ	00000000500000000r		; 1.061e-313
__unwindtable$?what@Exception@@UBEPBDXZ DD 0ffffffffH
	DD	FLAT:___std_terminate
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$?GetOriginString@Exception@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ DQ 00000000119930522r ; 2.33398e-314
	DD	FLAT:__unwindtable$?GetOriginString@Exception@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
	DQ	00000000000000000r		; 0
	DQ	00000000000000000r		; 0
	DQ	00000000500000000r		; 1.061e-313
__unwindtable$?GetOriginString@Exception@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ DD 0ffffffffH
	DD	FLAT:___std_terminate
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z DQ 00000000719930522r ; 1.5066e-313
	DD	FLAT:__unwindtable$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z
	DD	01H
	DD	FLAT:__tryblocktable$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z
	DQ	00000000000000000r		; 0
	DQ	00000000100000000r		; 2.122e-314
__unwindtable$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z$4
	DD	0ffffffffH
	DD	FLAT:__unwindfunclet$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z$2
	DD	01H
	DD	FLAT:__unwindfunclet$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z$3
	DQ	00000000000000001r		; 4.94066e-324
	DQ	00000000000000001r		; 4.94066e-324
	DD	0ffffffffH
	DD	FLAT:___std_terminate
	DD	05H
	DD	FLAT:___std_terminate
__tryblocktable$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z DQ 00000000300000003r ; 6.36599e-314
	DQ	00000000100000004r		; 2.122e-314
	DD	FLAT:__catchsym$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z$7
__catchsym$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z$7 DQ 00000000000000040r ; 3.16202e-322
	DD	00H
	DD	FLAT:__catch$??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z$0
END
