; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

	TITLE	f:\windowsandbox\windowsandbox\src\keyboard.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

END
