; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

	TITLE	F:\WindowSandbox\WindowSandbox\src\Window.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__7242C389_ctype@h DB 01H
__90A1F774_basetsd@h DB 01H
__367CC694_corecrt_memcpy_s@h DB 01H
__35D7DDB3_corecrt_memory@h DB 01H
__DC9673E3_corecrt_wstring@h DB 01H
__A29A7DFB_string@h DB 01H
__3C23D660_guiddef@h DB 01H
__AF541008_winnt@h DB 01H
__0D001789_processthreadsapi@h DB 01H
__F972325D_memoryapi@h DB 01H
__76CD430D_winerror@h DB 01H
__737D49DB_winbase@h DB 01H
__1B9502AC_winuser@h DB 01H
__376EBCA0_winioctl@h DB 01H
__24E9E95F_stdlib@h DB 01H
__2CCBBE23_propidl@h DB 01H
__AD360DAF_oleauto@h DB 01H
__0396F1A5_stralign@h DB 01H
__D8B84C1C_Window@h DB 01H
__EA726F75_Window@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?GetName@WindowClass@Window@@SAPBDXZ		; Window::WindowClass::GetName
PUBLIC	?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ ; Window::WindowClass::GetInstance
PUBLIC	??0WindowClass@Window@@AAE@XZ			; Window::WindowClass::WindowClass
PUBLIC	??1WindowClass@Window@@AAE@XZ			; Window::WindowClass::~WindowClass
PUBLIC	?__autoclassinit2@WindowClass@Window@@QAEXI@Z	; Window::WindowClass::__autoclassinit2
PUBLIC	??0Window@@QAE@HHPBD@Z				; Window::Window
PUBLIC	??1Window@@QAE@XZ				; Window::~Window
PUBLIC	?HandleMsgSetup@Window@@CGJPAUHWND__@@IIJ@Z	; Window::HandleMsgSetup
PUBLIC	?HandleMsgThunk@Window@@CGJPAUHWND__@@IIJ@Z	; Window::HandleMsgThunk
PUBLIC	?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z		; Window::HandleMsg
PUBLIC	__JustMyCode_Default
PUBLIC	?wndClassName@WindowClass@Window@@0QBDB		; Window::WindowClass::wndClassName
PUBLIC	??_C@_07KHIJMDBA@SandBox@			; `string'
PUBLIC	?wndClass@WindowClass@Window@@0V12@A		; Window::WindowClass::wndClass
EXTRN	_atexit:PROC
EXTRN	__imp__GetModuleHandleA@4:PROC
EXTRN	__imp__DefWindowProcA@16:PROC
EXTRN	__imp__PostQuitMessage@4:PROC
EXTRN	__imp__UnregisterClassA@8:PROC
EXTRN	__imp__RegisterClassExA@4:PROC
EXTRN	__imp__CreateWindowExA@48:PROC
EXTRN	__imp__DestroyWindow@4:PROC
EXTRN	__imp__ShowWindow@8:PROC
EXTRN	__imp__GetWindowLongA@8:PROC
EXTRN	__imp__SetWindowLongA@12:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	___CxxFrameHandler3:PROC
EXTRN	_memset:PROC
EXTRN	___security_cookie:DWORD
_BSS	SEGMENT
?wndClass@WindowClass@Window@@0V12@A DD 01H DUP (?)	; Window::WindowClass::wndClass
_BSS	ENDS
CRT$XCU	SEGMENT
??wndClass$initializer$@WindowClass@Window@@0P6AXXZA@@3P6AXXZA DD FLAT:??__E?wndClass@WindowClass@Window@@0V12@A@@YAXXZ ; ??wndClass$initializer$@WindowClass@Window@@0P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_07KHIJMDBA@SandBox@
CONST	SEGMENT
??_C@_07KHIJMDBA@SandBox@ DB 'SandBox', 00H		; `string'
CONST	ENDS
;	COMDAT ?wndClassName@WindowClass@Window@@0QBDB
CONST	SEGMENT
?wndClassName@WindowClass@Window@@0QBDB DD FLAT:??_C@_07KHIJMDBA@SandBox@ ; Window::WindowClass::wndClassName
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$?HandleMsgThunk@Window@@CGJPAUHWND__@@IIJ@Z DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$?HandleMsgSetup@Window@@CGJPAUHWND__@@IIJ@Z DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??1Window@@QAE@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??0Window@@QAE@HHPBD@Z DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??1WindowClass@Window@@AAE@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??0WindowClass@Window@@AAE@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$?GetName@WindowClass@Window@@SAPBDXZ DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??__F?wndClass@WindowClass@Window@@0V12@A@@YAXXZ
text$yd	SEGMENT
??__F?wndClass@WindowClass@Window@@0V12@A@@YAXXZ PROC	; `dynamic atexit destructor for 'Window::WindowClass::wndClass'', COMDAT
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET ?wndClass@WindowClass@Window@@0V12@A ; Window::WindowClass::wndClass
	call	??1WindowClass@Window@@AAE@XZ		; Window::WindowClass::~WindowClass
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??__F?wndClass@WindowClass@Window@@0V12@A@@YAXXZ ENDP	; `dynamic atexit destructor for 'Window::WindowClass::wndClass''
text$yd	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??__E?wndClass@WindowClass@Window@@0V12@A@@YAXXZ
text$di	SEGMENT
??__E?wndClass@WindowClass@Window@@0V12@A@@YAXXZ PROC	; `dynamic initializer for 'Window::WindowClass::wndClass'', COMDAT
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 3
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
	push	4
	mov	ecx, OFFSET ?wndClass@WindowClass@Window@@0V12@A ; Window::WindowClass::wndClass
	call	?__autoclassinit2@WindowClass@Window@@QAEXI@Z
	mov	ecx, OFFSET ?wndClass@WindowClass@Window@@0V12@A ; Window::WindowClass::wndClass
	call	??0WindowClass@Window@@AAE@XZ		; Window::WindowClass::WindowClass
	push	OFFSET ??__F?wndClass@WindowClass@Window@@0V12@A@@YAXXZ ; `dynamic atexit destructor for 'Window::WindowClass::wndClass''
	call	_atexit
	add	esp, 4
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??__E?wndClass@WindowClass@Window@@0V12@A@@YAXXZ ENDP	; `dynamic initializer for 'Window::WindowClass::wndClass''
text$di	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z
_TEXT	SEGMENT
tv64 = -220						; size = 4
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
_hWnd$ = 8						; size = 4
_msg$ = 12						; size = 4
_wParam$ = 16						; size = 4
_lParam$ = 20						; size = 4
?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z PROC		; Window::HandleMsg, COMDAT
; _this$ = ecx
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 85
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 208				; 000000d0H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-220]
	mov	ecx, 52					; 00000034H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 86
	mov	eax, DWORD PTR _msg$[ebp]
	mov	DWORD PTR tv64[ebp], eax
	cmp	DWORD PTR tv64[ebp], 16			; 00000010H
	je	SHORT $LN4@HandleMsg
	jmp	SHORT $LN2@HandleMsg
$LN4@HandleMsg:
; Line 91
	mov	esi, esp
	push	0
	call	DWORD PTR __imp__PostQuitMessage@4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 92
	xor	eax, eax
	jmp	SHORT $LN5@HandleMsg
$LN2@HandleMsg:
; Line 95
	mov	esi, esp
	mov	eax, DWORD PTR _lParam$[ebp]
	push	eax
	mov	ecx, DWORD PTR _wParam$[ebp]
	push	ecx
	mov	edx, DWORD PTR _msg$[ebp]
	push	edx
	mov	eax, DWORD PTR _hWnd$[ebp]
	push	eax
	call	DWORD PTR __imp__DefWindowProcA@16
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN5@HandleMsg:
; Line 96
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 220				; 000000dcH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-224]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z ENDP		; Window::HandleMsg
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?HandleMsgThunk@Window@@CGJPAUHWND__@@IIJ@Z
_TEXT	SEGMENT
_pWnd$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
_hWnd$ = 8						; size = 4
_msg$ = 12						; size = 4
_wParam$ = 16						; size = 4
_lParam$ = 20						; size = 4
?HandleMsgThunk@Window@@CGJPAUHWND__@@IIJ@Z PROC	; Window::HandleMsgThunk, COMDAT
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 77
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?HandleMsgThunk@Window@@CGJPAUHWND__@@IIJ@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 79
	mov	esi, esp
	push	-21					; ffffffebH
	mov	eax, DWORD PTR _hWnd$[ebp]
	push	eax
	call	DWORD PTR __imp__GetWindowLongA@8
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _pWnd$[ebp], eax
; Line 81
	mov	eax, DWORD PTR _lParam$[ebp]
	push	eax
	mov	ecx, DWORD PTR _wParam$[ebp]
	push	ecx
	mov	edx, DWORD PTR _msg$[ebp]
	push	edx
	mov	eax, DWORD PTR _hWnd$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pWnd$[ebp]
	call	?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z	; Window::HandleMsg
; Line 82
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$?HandleMsgThunk@Window@@CGJPAUHWND__@@IIJ@Z:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?HandleMsgThunk@Window@@CGJPAUHWND__@@IIJ@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?HandleMsgThunk@Window@@CGJPAUHWND__@@IIJ@Z ENDP	; Window::HandleMsgThunk
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?HandleMsgSetup@Window@@CGJPAUHWND__@@IIJ@Z
_TEXT	SEGMENT
_pWnd$2 = -32						; size = 4
_pCreate$3 = -20					; size = 4
__$EHRec$ = -12						; size = 12
_hWnd$ = 8						; size = 4
_msg$ = 12						; size = 4
_wParam$ = 16						; size = 4
_lParam$ = 20						; size = 4
?HandleMsgSetup@Window@@CGJPAUHWND__@@IIJ@Z PROC	; Window::HandleMsgSetup, COMDAT
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 58
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?HandleMsgSetup@Window@@CGJPAUHWND__@@IIJ@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 60
	cmp	DWORD PTR _msg$[ebp], 129		; 00000081H
	jne	SHORT $LN2@HandleMsgS
; Line 63
	mov	eax, DWORD PTR _lParam$[ebp]
	mov	DWORD PTR _pCreate$3[ebp], eax
; Line 64
	mov	eax, DWORD PTR _pCreate$3[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _pWnd$2[ebp], ecx
; Line 66
	mov	esi, esp
	mov	eax, DWORD PTR _pWnd$2[ebp]
	push	eax
	push	-21					; ffffffebH
	mov	ecx, DWORD PTR _hWnd$[ebp]
	push	ecx
	call	DWORD PTR __imp__SetWindowLongA@12
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 68
	mov	esi, esp
	push	OFFSET ?HandleMsgThunk@Window@@CGJPAUHWND__@@IIJ@Z ; Window::HandleMsgThunk
	push	-4					; fffffffcH
	mov	eax, DWORD PTR _hWnd$[ebp]
	push	eax
	call	DWORD PTR __imp__SetWindowLongA@12
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 70
	mov	eax, DWORD PTR _lParam$[ebp]
	push	eax
	mov	ecx, DWORD PTR _wParam$[ebp]
	push	ecx
	mov	edx, DWORD PTR _msg$[ebp]
	push	edx
	mov	eax, DWORD PTR _hWnd$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pWnd$2[ebp]
	call	?HandleMsg@Window@@AAEJPAUHWND__@@IIJ@Z	; Window::HandleMsg
	jmp	SHORT $LN3@HandleMsgS
$LN2@HandleMsgS:
; Line 73
	mov	esi, esp
	mov	eax, DWORD PTR _lParam$[ebp]
	push	eax
	mov	ecx, DWORD PTR _wParam$[ebp]
	push	ecx
	mov	edx, DWORD PTR _msg$[ebp]
	push	edx
	mov	eax, DWORD PTR _hWnd$[ebp]
	push	eax
	call	DWORD PTR __imp__DefWindowProcA@16
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@HandleMsgS:
; Line 74
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 228				; 000000e4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$?HandleMsgSetup@Window@@CGJPAUHWND__@@IIJ@Z:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-232]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?HandleMsgSetup@Window@@CGJPAUHWND__@@IIJ@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?HandleMsgSetup@Window@@CGJPAUHWND__@@IIJ@Z ENDP	; Window::HandleMsgSetup
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??1Window@@QAE@XZ
_TEXT	SEGMENT
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
??1Window@@QAE@XZ PROC					; Window::~Window, COMDAT
; _this$ = ecx
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 53
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??1Window@@QAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 54
	mov	esi, esp
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	push	ecx
	call	DWORD PTR __imp__DestroyWindow@4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 55
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$??1Window@@QAE@XZ:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??1Window@@QAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1Window@@QAE@XZ ENDP					; Window::~Window
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??0Window@@QAE@HHPBD@Z
_TEXT	SEGMENT
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
_width$ = 8						; size = 4
_height$ = 12						; size = 4
_name$ = 16						; size = 4
??0Window@@QAE@HHPBD@Z PROC				; Window::Window, COMDAT
; _this$ = ecx
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 40
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??0Window@@QAE@HHPBD@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 42
	mov	esi, esp
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	call	?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ ; Window::WindowClass::GetInstance
	push	eax
	push	0
	push	0
	push	256					; 00000100H
	push	512					; 00000200H
	push	-2147483648				; 80000000H
	push	-2147483648				; 80000000H
	push	13238272				; 00ca0000H
	mov	ecx, DWORD PTR _name$[ebp]
	push	ecx
	call	?GetName@WindowClass@Window@@SAPBDXZ	; Window::WindowClass::GetName
	push	eax
	push	0
	call	DWORD PTR __imp__CreateWindowExA@48
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+8], eax
; Line 49
	mov	esi, esp
	push	10					; 0000000aH
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	push	ecx
	call	DWORD PTR __imp__ShowWindow@8
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 50
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$??0Window@@QAE@HHPBD@Z:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??0Window@@QAE@HHPBD@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
??0Window@@QAE@HHPBD@Z ENDP				; Window::Window
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?__autoclassinit2@WindowClass@Window@@QAEXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_classSize$ = 8						; size = 4
?__autoclassinit2@WindowClass@Window@@QAEXI@Z PROC	; Window::WindowClass::__autoclassinit2, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _classSize$[ebp]
	push	eax
	push	0
	mov	ecx, DWORD PTR _this$[ebp]
	push	ecx
	call	_memset
	add	esp, 12					; 0000000cH
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?__autoclassinit2@WindowClass@Window@@QAEXI@Z ENDP	; Window::WindowClass::__autoclassinit2
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??1WindowClass@Window@@AAE@XZ
_TEXT	SEGMENT
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
??1WindowClass@Window@@AAE@XZ PROC			; Window::WindowClass::~WindowClass, COMDAT
; _this$ = ecx
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 25
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??1WindowClass@Window@@AAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 26
	call	?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ ; Window::WindowClass::GetInstance
	mov	esi, esp
	push	eax
	mov	eax, DWORD PTR ?wndClassName@WindowClass@Window@@0QBDB
	push	eax
	call	DWORD PTR __imp__UnregisterClassA@8
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 27
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$??1WindowClass@Window@@AAE@XZ:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??1WindowClass@Window@@AAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1WindowClass@Window@@AAE@XZ ENDP			; Window::WindowClass::~WindowClass
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??0WindowClass@Window@@AAE@XZ
_TEXT	SEGMENT
_wc$ = -80						; size = 48
_this$ = -24						; size = 4
__$ArrayPad$ = -16					; size = 4
__$EHRec$ = -12						; size = 12
??0WindowClass@Window@@AAE@XZ PROC			; Window::WindowClass::WindowClass, COMDAT
; _this$ = ecx
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 8
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??0WindowClass@Window@@AAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 264				; 00000108H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-276]
	mov	ecx, 66					; 00000042H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 7
	mov	esi, esp
	push	0
	call	DWORD PTR __imp__GetModuleHandleA@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 9
	push	48					; 00000030H
	push	0
	lea	eax, DWORD PTR _wc$[ebp]
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
; Line 10
	mov	DWORD PTR _wc$[ebp], 48			; 00000030H
; Line 11
	mov	DWORD PTR _wc$[ebp+4], 32		; 00000020H
; Line 12
	mov	DWORD PTR _wc$[ebp+8], OFFSET ?HandleMsgSetup@Window@@CGJPAUHWND__@@IIJ@Z ; Window::HandleMsgSetup
; Line 13
	mov	DWORD PTR _wc$[ebp+12], 0
; Line 14
	mov	DWORD PTR _wc$[ebp+16], 0
; Line 15
	call	?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ ; Window::WindowClass::GetInstance
	mov	DWORD PTR _wc$[ebp+20], eax
; Line 16
	mov	DWORD PTR _wc$[ebp+24], 0
; Line 17
	mov	DWORD PTR _wc$[ebp+28], 0
; Line 18
	mov	DWORD PTR _wc$[ebp+32], 0
; Line 19
	mov	DWORD PTR _wc$[ebp+36], 0
; Line 20
	call	?GetName@WindowClass@Window@@SAPBDXZ	; Window::WindowClass::GetName
	mov	DWORD PTR _wc$[ebp+40], eax
; Line 21
	mov	DWORD PTR _wc$[ebp+44], 0
; Line 22
	mov	esi, esp
	lea	eax, DWORD PTR _wc$[ebp]
	push	eax
	call	DWORD PTR __imp__RegisterClassExA@4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 23
	mov	eax, DWORD PTR _this$[ebp]
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN6@WindowClas
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 276				; 00000114H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	1
$LN6@WindowClas:
	DD	1
	DD	$LN5@WindowClas
$LN5@WindowClas:
	DD	-80					; ffffffb0H
	DD	48					; 00000030H
	DD	$LN3@WindowClas
$LN3@WindowClas:
	DB	119					; 00000077H
	DB	99					; 00000063H
	DB	0
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$??0WindowClass@Window@@AAE@XZ:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-280]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-4]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??0WindowClass@Window@@AAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??0WindowClass@Window@@AAE@XZ ENDP			; Window::WindowClass::WindowClass
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ
_TEXT	SEGMENT
__$EHRec$ = -12						; size = 12
?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ PROC ; Window::WindowClass::GetInstance, COMDAT
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 33
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 34
	mov	eax, DWORD PTR ?wndClass@WindowClass@Window@@0V12@A ; Window::WindowClass::wndClass
; Line 35
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-208]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?GetInstance@WindowClass@Window@@SAPAUHINSTANCE__@@XZ ENDP ; Window::WindowClass::GetInstance
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?GetName@WindowClass@Window@@SAPBDXZ
_TEXT	SEGMENT
__$EHRec$ = -12						; size = 12
?GetName@WindowClass@Window@@SAPBDXZ PROC		; Window::WindowClass::GetName, COMDAT
; File F:\WindowSandbox\WindowSandbox\src\Window.cpp
; Line 29
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?GetName@WindowClass@Window@@SAPBDXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	ecx, OFFSET __EA726F75_Window@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 30
	mov	eax, DWORD PTR ?wndClassName@WindowClass@Window@@0QBDB
; Line 31
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	int	3
	int	3
	int	3
	int	3
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$?GetName@WindowClass@Window@@SAPBDXZ:
	npad	1
	npad	1
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-208]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?GetName@WindowClass@Window@@SAPBDXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?GetName@WindowClass@Window@@SAPBDXZ ENDP		; Window::WindowClass::GetName
END
